/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;

/**
 *
 * @author jorge
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn_view = new javax.swing.JButton();
        Btn_add = new javax.swing.JButton();
        Btn_delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        javax.swing.GroupLayout Panel_DesktopLayout = new javax.swing.GroupLayout(Panel_Desktop);
        Panel_Desktop.setLayout(Panel_DesktopLayout);
        Panel_DesktopLayout.setHorizontalGroup(
            Panel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        Panel_DesktopLayout.setVerticalGroup(
            Panel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(110, 0, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agenda");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/book.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(248, 248, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_view.setBackground(new java.awt.Color(248, 248, 251));
        Btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Eye.png"))); // NOI18N
        Btn_view.setBorder(null);
        Btn_view.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Eye_opc.png"))); // NOI18N
        jPanel2.add(Btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 236, -1, -1));

        Btn_add.setBackground(new java.awt.Color(248, 248, 251));
        Btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Add.png"))); // NOI18N
        Btn_add.setBorder(null);
        Btn_add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Add_opc.png"))); // NOI18N
        jPanel2.add(Btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 75, 75));

        Btn_delete.setBackground(new java.awt.Color(248, 248, 251));
        Btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Garbaje.png"))); // NOI18N
        Btn_delete.setBorder(null);
        Btn_delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Images&Icons/Garbaje_opc.png"))); // NOI18N
        jPanel2.add(Btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 143, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 0, 255));
        jLabel3.setText("Ver");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 0, 255));
        jLabel4.setText("Opciones");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 0, 255));
        jLabel5.setText("Añadir");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 0, 255));
        jLabel6.setText("Borrar");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_Desktop)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtn_add() {
        return Btn_add;
    }

    public void setBtn_add(JButton Btn_add) {
        this.Btn_add = Btn_add;
    }

    public JButton getBtn_delete() {
        return Btn_delete;
    }

    public void setBtn_delete(JButton Btn_delete) {
        this.Btn_delete = Btn_delete;
    }

    public JButton getBtn_view() {
        return Btn_view;
    }

    public void setBtn_view(JButton Btn_view) {
        this.Btn_view = Btn_view;
    }

    public JDesktopPane getPanel_Desktop() {
        return Panel_Desktop;
    }

    public void setPanel_Desktop(JDesktopPane Panel_Desktop) {
        this.Panel_Desktop = Panel_Desktop;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_add;
    private javax.swing.JButton Btn_delete;
    private javax.swing.JButton Btn_view;
    private javax.swing.JDesktopPane Panel_Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
